package com.bbva.wallet.enums;

public enum ErrorCodes {
    VALOR_INVALIDO, USUARIO_YA_CREADO,USUARIO_NO_ENCONTRADO,CUENTA_YA_CREADA,CUENTA_NO_ENCONTRADA,
    NO_COINCIDEN_TIPO_DE_MONEDAS,SALDO_INSUFICIENTE,SUPERASTE_LIMITE_DE_TRANSACCION,
    TRANSACCION_NO_PERMITIDA, USUARIO_SIN_PERMISOS, TRANSACCION_NO_EXISTE,CANTIDAD_NO_PERMITIDA,CANTIDAD_MESES_INVALIDA, USUARIO_SIN_TRANSACCIONES,
}
